[package]
name = "main"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jobs = {path = "../jobs"}
job_threads = {path = "../job_threads"}
services = {path = "../services"}